-- SQL para inicializar el esquema de Nexora en Supabase

-- 1. User Profile Management (Bilateral registration)
create type user_role as enum ('EMPRESA', 'CONSULTOR');

create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  city text,
  user_type user_role not null,
  created_at timestamp with time zone default now()
);

-- 2. Consultant specific data
create table public.consultants (
  id uuid references public.profiles on delete cascade primary key,
  role text not null,
  rating decimal default 0,
  projects integer default 0,
  experience_years integer not null,
  age integer,
  bio text,
  expertise text[] default '{}',
  verified boolean default false,
  updated_at timestamp with time zone default now()
);

-- 3. Favorite Consultants (for companies)
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  consultant_id uuid references public.consultants on delete cascade not null,
  created_at timestamp with time zone default now(),
  unique(user_id, consultant_id)
);

-- 4. Messaging System
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles on delete cascade not null,
  receiver_id uuid references public.profiles on delete cascade not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default now()
);

-- 5. Row Level Security (RLS) Policies
alter table public.profiles enable row level security;
alter table public.consultants enable row level security;
alter table public.favorites enable row level security;
alter table public.messages enable row level security;

-- Profiles: Users can only see their own profile or public consultant profiles
create policy "Public profiles are viewable by everyone" 
on public.profiles for select using (true);

create policy "Users can update own profile" 
on public.profiles for update using (auth.uid() = id);

-- Consultants: All consultants are public
create policy "Consultants are viewable by everyone" 
on public.consultants for select using (true);

-- Favorites: Only owners can manage favorites
create policy "Users can manage their own favorites" 
on public.favorites for all using (auth.uid() = user_id);

-- Messages: Users can only see messages sent to or from them
create policy "Users can see their own messages" 
on public.messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Users can send messages" 
on public.messages for insert with check (auth.uid() = sender_id);
