-- Gestión de expertos favoritos
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  consultant_id uuid references public.consultants on delete cascade not null,
  created_at timestamp with time zone default now(),
  unique(user_id, consultant_id)
);
